import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"

export default function Home() {
	return (
		<>
			<Head>
				<title>Musica</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/logo.svg'
				/>
			</Head>
			<main></main>
		</>
	)
}
